// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "ISprime Origins API": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/maurodelazeri/image-uploader/design
// --out=$(GOPATH)/src/github.com/maurodelazeri/image-uploader
// --version=v1.3.0

package app

import (
	"fmt"
	"strings"
)

// ImageHref returns the resource href.
func ImageHref(id interface{}) string {
	paramid := strings.TrimLeftFunc(fmt.Sprintf("%v", id), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/api/images/%v", paramid)
}
