// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "ISprime Origins API": Application User Types
//
// Command:
// $ goagen
// --design=github.com/maurodelazeri/image-uploader/design
// --out=$(GOPATH)/src/github.com/maurodelazeri/image-uploader
// --version=v1.3.0

package app
